Improve find
sergiors/functional pull request #12
Opened 2016-10-31 20:23 UTC by sergiors

\cc @haskellcamargo

2016-10-31 20:41 UTC, sergiors commented
lgtm

2016-11-01 02:14 UTC, haskellcamargo requested changes

2016-11-01 02:14 UTC, haskellcamargo commented on src/find.php
> +        return ifelse(equals([]), always(null), function (array $xss) use ($pred) {
Wouldn't be better to make them standard? `ifElse` instead of `ifelse`.

2016-11-01 13:58 UTC, sergiors commented on src/find.php
> +        return ifelse(equals([]), always(null), function (array $xss) use ($pred) {
yep, I also need to rename other fns like `getin`-> `getIn`

2016-11-01 14:15 UTC, sergiors commented on src/find.php
> +        return ifelse(equals([]), always(null), function (array $xss) use ($pred) {
done!

2016-11-01 16:22 UTC, haskellcamargo approved these changes
LGTM

2016-11-01 16:28 UTC, sergiors commented
self lgtm

2016-11-01 16:28 UTC, merged